#!/bin/bash
#
# Fix bspwm padding and spawn (poly)bar
# 
# LEFT = 0x00800003
# MAIN = 0x00800005
# RIGHT = 0x00800001
if [ $DEBUG == "1" ]; then
  set -x
fi

SCREENS=$(bspc query -M | wc -l)
SCRARR="$(bspc query -M)"
PolyState=$(pgrep -c polybar)
PolyPID=$(pgrep polybar)
PolyCMD="polybar example"

# Set MAIN and Monitor if we have more than 1 screen
if [ $SCREENS > '2' ]; then
	MAIN='0x00A00005'
	MONITOR=$(xrandr | awk '/ primary/ { print $1 }')
else
	MONITOR="LVDS-1"
fi

#Killing bar if it's running before spawning a new one
while [ $PolyState -eq '1' ]; do
	COUNT=0
	while [ $COUNT -lt 10 ]; do
		kill -9 $PolyPID
    RET=$?
    if [ $RET -gt "0" ]; then
		  let COUNT=COUNT+1
    else
      break 3
    fi
		sleep 2
    PolyState=$(pgrep -c polybar)
	done
done

if [ ! -z $MONITOR ]; then
  printf "start PolyCMD: %s" "$PolyCMD"
	$PolyCMD > /dev/null 2>&1 &
fi

# Fix the screen padding
for screens in ${SCRARR[@]}; do
  printf "Setting screen: %s" "$screens"
	if [ $screens == "$MAIN" ]; then
		bspc config -m $screens top_padding 30
	else
		bspc config -m $screens top_padding 5
  fi
  sleep 0.5
done

# Restore wallpapers
[[ -e /usr/bin/nitrogen ]] && nitrogen --restore
