#!/bin/bash
#
# Fix bspwm padding and spawn (poly)bar
# 
# LEFT = 0x00800003
# MAIN = 0x00800005
# RIGHT = 0x00800001

SCREENS=$(bspc query -M | wc -l)
SCRARR='$(bspc query -M)'
PolyState=$(pgrep -c polybar)
PolyPID=$(pgrep polybar)
PolyCMD="polybar example > /dev/null 2>&1"

# Set MAIN and Monitor if we have more than 1 screen
if [ $SCREENS > '2' ]; then
	MAIN='0x00800005'
	MONITOR=$(xrandr | awk '/ primary/ { print $1 }')
else
	MONITOR="LVDS-1"
fi

# Fix the screen padding
for screens in ${SCRARR[@]}; do
	if [ $screens == '$MAIN' ]; then
		bspc config -m $screens top_padding 30
	else
		bspc config -m $screens top_padding 5
	fi
done

#Killing bar if it's running before spawning a new one
while [[ $PolyState -eq '1' ]]; do
	COUNT=0
	while [ $COUNT -lt 10 ]; do
		kill -9 $PolyPID
		let COUNT=COUNT+1
		sleep 2
	done
done

if [ ! -z $MONITOR ]; then
	$PolyCMD
fi