#!/bin/bash

source $(dirname $0)/panel_colors

DISKS=`lsblk | grep /dev/sdb`
MOUNT=`$DISKS | awk '{print $6}'`

ICON="^i($PANEL_ICON_DIR/usb.xbm)"
if [ "$($DISKS)" ]; then
	echo "^fg($PANEL_COLOR_ICON)$ICON ^fg($PANEL_COLOR_TEXT)$MOUNT"
else
	echo "^fg($PANEL_COLOR_ICON)$ICON"
fi
