#!/bin/bash

source $(dirname $0)/panel_colors

TIME=`date +%r`

ICON="^i($PANEL_ICON_DIR/clock.xbm)"
INFO_ICON="^i($PANEL_ICON_DIR/info_03.xbm)"
echo "^fg($PANEL_COLOR_ICON)$ICON ^fg($PANEL_COLOR_TEXT)$TIME  ^fg($PANEL_COLOR_ICON)^ca(1, ./popup_info)$INFO_ICON^ca()"
