#!/bin/bash

source $(dirname $0)/panel_colors

CPUP=`grep "cpu " /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}' | cut -c 1-4`
CPUTEMP=`sensors | grep "CPU Temp" | awk '{print $3}'`
CPUFREQ=`echo $( lscpu | grep "CPU MHz" | awk '{print $3}') / 1000 | bc | cut -c 1-4`
CPUBARUSED=`echo $CPUP / 2 | bc | awk '{print int($1+0.5)}'`

cpubar() {
	echo "^fg($PANEL_COLOR_BAR)^r(${CPUBARUSED}x${PROGRESSBAR_HEIGHT})^fg(darkgrey)^r($(( 50 - $CPUBARUSED ))x${PROGRESSBAR_HEIGHT})"
}

ICON="^i($PANEL_ICON_DIR/cpu.xbm)"
#echo "^ca(1,./popup_cpu)^fg($PANEL_COLOR_ICON)$ICON^ca() ^fg($PANEL_COLOR_TEXT)CPU: $CPUP%"
#echo "^fg($PANEL_COLOR_ICON)$ICON $(cpubar) ^fg($PANEL_COLOR_TEXT)$CPUP%  ${CPUFREQ}GHz  $CPUTEMP"
echo "^fg($PANEL_COLOR_ICON)^ca(1, ./popup_cpu)$ICON^ca() $(cpubar)"
