#!/bin/bash

source $(dirname $0)/popup_colors

PIPE=/tmp/pipe_wifi

ACT='onstart=uncollapse;button1=exit;button3=exit'
WIDTH=150
LINES=2
XPOS=1540
YPOS=15

[ -e $PIPE ] && rm "$PIPE"
mkfifo $PIPE

while true; do
  SSID=`iwgetid --raw`
  IIP=`ifconfig | grep "192.168" | awk '{print $2}'`

  echo "Networking"
  echo "SSID: $SSID"
  echo "IIP: $IIP"
  sleep 1
done > "$PIPE" &

cat "$PIPE" | dzen2 -u -p -bg $COLOR_BACKGROUND -fg $COLOR_FOREGROUND -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -x $XPOS -y $YPOS -w $WIDTH -l $LINES -sa 'l' -ta 'c' -e "$ACT" -title-name 'popup_wifi'
