#!/bin/sh

# config options
bspc config border_width            1
bspc config top_padding             0
bspc config window_gap              0
bspc config split_ratio             0.60
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true

# desktops
# bspc monitor -d main web term misc foo
desktops=$(bspc query -M)

echo "$desktops" | grep -q "[a-zA-Z]"
if [ $? -eq 0 ]; then IsInitialRun=true; else IsInitialRun=false; fi

#rename all the monitors to numbers and create 5 workspaces on each
i=1

for monitor in $desktops; do
    [ "$IsInitialRun" = true ] && \
        bspc monitor "$monitor" -n $i -d $i/{i,ii,iii,iiii,iiiii} || \
        bspc monitor "$monitor" -d $i/{i,ii,iii,iiii,iiiii}
    let i++
done
# desktops_con=$(bspc query -M | wc -l)
# if [ $desktops_con -lt 3 ]; then
# 	bspc monitor "$deskops" -d Main Term Web Media Other
# else
# 	i=1
# 	for monitor in $desktops; do
# 		bspc monitor $monitor -n $i -d $i\.{Main,Term,Web,Media,Other}
# 	done
# fi

# Desktop fixing
bspc desktop ^2 -l monocle
bspc desktop ^1 -t floating=on
bspc desktop 2/1 -t floating=on

# Rules
# bspc rule -a Firefox desktop=^2
# bspc rule -a Gimp-2.8 desktop=^4 floating=on
# bspc rule -a Gimp desktop=^4 floating=on
# bspc rule -a deadbeef floating=on
# bspc rule -a transmission-gtk desktop=^5
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true
# bspc rule -a file-roller floating=on center=true

# colors
bspc config focused_border_color "#f0f0f0"
bspc config normal_border_color "#6C6C6C"
bspc config active_border_color "#6C6C6C"
bspc config focused_locked_border_color "#00C7D8"
bspc config normal_locked_border_color "#6C6C6C"
bspc config active_locked_border_color "#6C6C6C"
bspc config urgent_border_color "#CB4B16"
bspc config presel_border_color "#ee6666"

# Set fonts
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp /usr/share/fonts/envypn
xset fp rehash

# Autostart apps
# urxvt &
#compton &
numlockx &
#(sleep 10 && setroot --on 2 --blur 5 ~/Dropbox/Public/wp_mix/sky_lanterns_by_wlop-d7b5nfg.jpg --on 1 --blur 5 ~/Dropbox/Public/wp_mix/here__at_the_end_of_all_the_things__by_darrengeers-d73dy37.jpg --on 0 --blur 5 ~/Dropbox/Public/wp_mix/wallhaven-2018.jpg) &
xsetroot -cursor_name left_ptr &
#(sleep 10 && bspwm_panel.sh) &
#nitrogen --restore &
#if [ $(ps -cx | grep panel | wc -l) -lt 3 ]; then
#    (cd $HOME/scripts && sleep 5 && restart_panel.sh) &
#fi
